Lab_7/Controllers/AdditionalInfoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseOfWorkers.Controllers
{
    [Authorize(Roles ="Manager")]
    public class AdditionalInfoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lab_7/Controllers/AllEmployeesController.cs
using Lab_7.Interfaces;
using Lab_7.Mocks;
using Lab_7.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab_7.Controllers
{
    [Authorize]
    public class AllEmployeesController : Controller
    {

        private readonly IEmployees _employeesService;

        public AllEmployeesController(IEmployees employeesService)
        {
            _employeesService = employeesService;
        }


        public IActionResult List()
        {
            var employees = _employeesService.employees;
            foreach (var employee in employees) { 
            Console.WriteLine(employee.Id);}
            return View(employees);
        }

       [HttpPost] public IActionResult Delete(int id)
        {
            
            _employeesService.DeleteEmployee(id);
            return RedirectToAction("List");


        }
       
        [HttpPost]
        public IActionResult Edit(Employees updatedEmployee)
        {
            _employeesService.UpdateEmployee(updatedEmployee); 
            return Json(new { success = true }); 
        }


    }
}

Lab_7/Views/Shared/_Layout.cshtml
@using Lab_7.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab_7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab_7.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="AllEmployees" asp-action="List">The database of workers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdditionalInfo" asp-action="Index">More information </a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item ms-auto">
                               
                                <form asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="d-inline">
                                    <button type="submit" class="btn btn-outline-danger">Logout</button>  
                                </form>
                            </li>
                        }
                        </li>
                    </ul>
                </div>
            </div>
      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab_7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>