Lab_7/Controllers/AddNewEmployeeController.cs
using Lab_7.Interfaces;
using Lab_7.Mocks;
using Lab_7.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Lab_7.Controllers
{
    public class AddNewEmployeeController : Controller
    {
        private readonly IEmployees _employeesService;

        public AddNewEmployeeController(IEmployees employeesService)
        {
            _employeesService = employeesService;
        }

      
        public IActionResult List()
        {
            var employees = _employeesService.employees; 
            return View(employees);
        }

      
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        public IActionResult Create(Employees newEmployee)
        {
            var employeeList = (_employeesService as MockEmployees).employees;
            if (ModelState.IsValid)
            {
                newEmployee.Id = employeeList.Any() ? employeeList.Max(x => x.Id) + 1 : 1;
               
                (_employeesService as MockEmployees)?.AddEmployee(newEmployee);

                
                return RedirectToAction("List", "AllEmployees");
            }
            return View(newEmployee);
        }

    }
}

Lab_7/Controllers/AllEmployeesController.cs
using Lab_7.Interfaces;
using Lab_7.Mocks;
using Lab_7.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab_7.Controllers
{
    [Authorize]
    public class AllEmployeesController : Controller
    {

        private readonly IEmployees _employeesService;

        public AllEmployeesController(IEmployees employeesService)
        {
            _employeesService = employeesService;
        }


        public IActionResult List()
        {
            var employees = _employeesService.employees;
            foreach (var employee in employees) { 
            Console.WriteLine(employee.Id);}
            return View(employees);
        }

       [HttpPost] public IActionResult Delete(int id)
        {
            
            _employeesService.DeleteEmployee(id);
            return RedirectToAction("List");


        }
       
        [HttpPost]
        public IActionResult Edit(Employees updatedEmployee)
        {
            _employeesService.UpdateEmployee(updatedEmployee); 
            return Json(new { success = true }); 
        }


    }
}

Lab_7/Controllers/SearchController.cs
using Lab_7.Interfaces;
using Lab_7.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Lab_7.Controllers
{
    public class SearchController : Controller
    {
        private readonly IEmployees _employeesService;


        public SearchController(IEmployees employeesService)
        {
            _employeesService = employeesService;

        }
        [HttpGet]
        public IActionResult ShowSearch(string lastName)
        {
            var employees = _employeesService.employees;

            
            var worker = employees.Where(e => e.LastName.Equals(lastName, StringComparison.OrdinalIgnoreCase)).ToList();
            return View("ShowSearch", worker);
        }
      
    }
}

Lab_7/Views/AllEmployees/List.cshtml
@model IEnumerable<Lab_7.Models.Employees>
@using Lab_7.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<h2>Employees List</h2>
@if(User.IsInRole("Manager")){
<form asp-controller="Search" asp-action="ShowSearch" method="get">
    <div class="form-group" style="display: flex; justify-content: flex-end; gap: 10px;">
        
        <input type="text" name="lastName" class="form-control" style="width: 200px;" placeholder="Search by Last Name"/>
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>
<a asp-controller="AddNewEmployee" asp-action="Create" class="btn btn-success">Add New Employee</a>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Data</th>
            <th>Department</th>
            <th>Salary</th>
            <th>Phone</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
                    <tr id="employee-@employee.Id">
                        <td>
                            <span class="text" id="firstName-text-@employee.Id">@employee.FirstName</span>
                            <input type="text" id="firstName-input-@employee.Id" class="form-control" value="@employee.FirstName" style="display:none;" />
                        </td>
                        <td>
                            <span class="text" id="lastName-text-@employee.Id">@employee.LastName</span>
                            <input type="text" id="lastName-input-@employee.Id" class="form-control" value="@employee.LastName" style="display:none;" />
                        </td>
                        <td>
                            <span class="text" id="email-text-@employee.Id">@employee.Email</span>
                            <input type="text" id="email-input-@employee.Id" class="form-control" value="@employee.Email" style="display:none;" />
                        </td>
                        <td>
                            <span class="text" id="date-text-@employee.Id">@employee.Date</span>
                            <input type="text" id="date-input-@employee.Id" class="form-control" value="@employee.Date" style="display:none;" />
                        </td>
                             <td>
                                <span class="text" id="date-text-@employee.Id">@employee.Department</span>
                                <input type="text" id="date-input-@employee.Id" class="form-control" value="@employee.Department" style="display:none;" />
                            </td>
                                 <td>
                                <span class="text" id="date-text-@employee.Id">@employee.Salary
                                </span>
                                <input type="text" id="date-input-@employee.Id" class="form-control" value="@employee.Salary" style="display:none;" />
                            </td>
                                 <td>
                                <span class="text" id="date-text-@employee.Id">@employee.Phone</span>
                                <input type="text" id="date-input-@employee.Id" class="form-control" value="@employee.Phone" style="display:none;" />
                            </td>
                        <td style="text-align:right;">
                            <div class="btn-group" role="group">
                                 <form asp-controller="AllEmployees" asp-action="Delete" method="post">
                                    <input type="hidden" name="id" value="@employee.Id" />
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this employee?')">Delete</button>
                                </form>
                                <button class="btn btn-warning" onclick="enableEditMode(@employee.Id)">Edit</button>
                            </div>
                            <button class="btn btn-success" id="save-btn-@employee.Id" style="display:none;" onclick="saveChanges(@employee.Id)">Save</button>
                        </td>
                    </tr>
        }
    </tbody>
</table>

<script>
    function enableEditMode(id) {
        document.getElementById('firstName-text-' + id).style.display = 'none';
        document.getElementById('lastName-text-' + id).style.display = 'none';
        document.getElementById('email-text-' + id).style.display = 'none';
        document.getElementById('date-text-' + id).style.display = 'none';

        document.getElementById('firstName-input-' + id).style.display = 'inline-block';
        document.getElementById('lastName-input-' + id).style.display = 'inline-block';
        document.getElementById('email-input-' + id).style.display = 'inline-block';
        document.getElementById('date-input-' + id).style.display = 'inline-block';

        document.getElementById('save-btn-' + id).style.display = 'inline-block';
    }

    function saveChanges(id) {
      
        var firstName = document.getElementById('firstName-input-' + id).value;
        var lastName = document.getElementById('lastName-input-' + id).value;
        var email = document.getElementById('email-input-' + id).value;
        var date = document.getElementById('date-input-' + id).value;

      
        $.ajax({
            url: '/AllEmployees/Edit',
            type: 'POST',
            data: {
                Id: id,
                FirstName: firstName,
                LastName: lastName,
                Email: email,
                DateTime: date
            },
            success: function (response) {
              
                document.getElementById('firstName-text-' + id).innerText = firstName;
                document.getElementById('lastName-text-' + id).innerText = lastName;
                document.getElementById('email-text-' + id).innerText = email;
                document.getElementById('date-text-' + id).innerText = date;

             
                document.getElementById('firstName-input-' + id).style.display = 'none';
                document.getElementById('lastName-input-' + id).style.display = 'none';
                document.getElementById('email-input-' + id).style.display = 'none';
                document.getElementById('date-input-' + id).style.display = 'none';

                document.getElementById('firstName-text-' + id).style.display = 'inline-block';
                document.getElementById('lastName-text-' + id).style.display = 'inline-block';
                document.getElementById('email-text-' + id).style.display = 'inline-block';
                document.getElementById('date-text-' + id).style.display = 'inline-block';

                document.getElementById('save-btn-' + id).style.display = 'none';
            },
            error: function (error) {
                alert('Error updating employee');
            }
        });
    }
    </script>
}
else if (User.IsInRole("Member"))
{
    <table class="table">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Department</th>
            
               
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model)
            {
                <tr id="employee-@employee.Id">
                    <td>
                        <span class="text" id="firstName-text-@employee.Id">@employee.FirstName</span>
                        <input type="text" id="firstName-input-@employee.Id" class="form-control" value="@employee.FirstName" style="display:none;" />
                    </td>
                    <td>
                        <span class="text" id="lastName-text-@employee.Id">@employee.LastName</span>
                        <input type="text" id="lastName-input-@employee.Id" class="form-control" value="@employee.LastName" style="display:none;" />
                    </td>
                    <td>
                        <span class="text" id="email-text-@employee.Id">@employee.Email</span>
                        <input type="text" id="email-input-@employee.Id" class="form-control" value="@employee.Email" style="display:none;" />
                    </td>
                   
                    <td>
                        <span class="text" id="date-text-@employee.Id">@employee.Department</span>
                        <input type="text" id="date-input-@employee.Id" class="form-control" value="@employee.Department" style="display:none;" />
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h2>You are not authorised to access the information on the page. If there is an error, please contact the manager</h2>
}